### ISSUE TITLE
Getting this error

### ISSUE THREAD

**Issue by parthmalhotra** [mdsecresearch/ThriftDecoder#1]
Hi Guys, Thanks for the module, I am getting the following error, Can someone help ?
`
problem parsing data in setMessage
 Traceback (most recent call last):
  File "/root/Desktop/root/ThriftDecoder/ThriftDecoder.py", line 231, in setMessage
    msg, msglen = ThriftMessage.read(data, read_values=True)
  File "/root/Desktop/root/ThriftDecoder/thrift_tools/thrift_message.py", line 127, in read
    method, mtype, seqid = proto.readMessageBegin()
  File "/root/Desktop/root/ThriftDecoder/thrift/protocol/TBinaryProtocol.py", line 148, in readMessageBegin
    name = self.trans.readAll(sz)
  File "/root/Desktop/root/ThriftDecoder/thrift/transport/TTransport.py", line 65, in readAll
    raise EOFError()
EOFError
`

**Comment by 0xra** [comment]
Hi 
Does it happen with all requests or just a few? The error is commonly encountered when the data is not actually thrift encoded or is corrupted 
Are you able to share the thrift-encoded data with us? Only the request that triggers the error is needed

**Comment by parthmalhotra** [comment]
Hello,

It is happening with all the requests, Will this sample data work? : https://gist.github.com/parthmalhotra/89c14f5f489c59f97cc968a6651bb556

Thanks.

**Comment by parthmalhotra** [comment]
Hey, Any update on this ?

**Comment by 0xra** [comment]
Hi, 
I've had a look at your sample data but not able to decode it, unfortunately. I believe it's a limitation in thrift-tools.
Since ThriftDecoder uses thrift-tools to do the decoding there are only a limited number of protocols supported. It may be that your data is using a protocol that thrift-tools is unable to decode such as fbthrift, finagle-thrift, finagle-mux, CORBA, etc.
thrift-tools decodes only Binary, Compact, and JSON protocols atm.
